# Generated by Django 5.1.3 on 2024-11-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0003_remove_investimento_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='valor',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
